# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/jose/python/proyecto_simulacion/simulacion/UI/simulation_widget.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_SimulationWindow(object):
    def setupUi(self, SimulationWindow):
        SimulationWindow.setObjectName(_fromUtf8("SimulationWindow"))
        SimulationWindow.resize(874, 559)
        self.centralwidget = QtGui.QWidget(SimulationWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.simBtn = QtGui.QPushButton(self.tab)
        self.simBtn.setEnabled(False)
        self.simBtn.setObjectName(_fromUtf8("simBtn"))
        self.gridLayout_2.addWidget(self.simBtn, 2, 0, 1, 1)
        self.groupBoxEventos = QtGui.QGroupBox(self.tab)
        self.groupBoxEventos.setEnabled(False)
        self.groupBoxEventos.setObjectName(_fromUtf8("groupBoxEventos"))
        self.gridLayout = QtGui.QGridLayout(self.groupBoxEventos)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_2 = QtGui.QLabel(self.groupBoxEventos)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.comboBoxEvProv = QtGui.QComboBox(self.groupBoxEventos)
        self.comboBoxEvProv.setObjectName(_fromUtf8("comboBoxEvProv"))
        self.gridLayout.addWidget(self.comboBoxEvProv, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBoxEventos)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.comboBoxEvPar = QtGui.QComboBox(self.groupBoxEventos)
        self.comboBoxEvPar.setObjectName(_fromUtf8("comboBoxEvPar"))
        self.gridLayout.addWidget(self.comboBoxEvPar, 1, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBoxEventos)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.dSpinBoxPerCent = QtGui.QDoubleSpinBox(self.groupBoxEventos)
        self.dSpinBoxPerCent.setMaximum(1000.0)
        self.dSpinBoxPerCent.setProperty("value", 100.0)
        self.dSpinBoxPerCent.setObjectName(_fromUtf8("dSpinBoxPerCent"))
        self.gridLayout.addWidget(self.dSpinBoxPerCent, 2, 1, 1, 1)
        self.logsBtn = QtGui.QPushButton(self.groupBoxEventos)
        self.logsBtn.setMaximumSize(QtCore.QSize(60, 16777215))
        self.logsBtn.setObjectName(_fromUtf8("logsBtn"))
        self.gridLayout.addWidget(self.logsBtn, 3, 0, 1, 1)
        self.updateEventBtn = QtGui.QPushButton(self.groupBoxEventos)
        self.updateEventBtn.setObjectName(_fromUtf8("updateEventBtn"))
        self.gridLayout.addWidget(self.updateEventBtn, 3, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBoxEventos, 10, 0, 1, 1)
        self.tabWidget_2 = QtGui.QTabWidget(self.tab)
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.tableWidget1 = QtGui.QTableWidget(self.tab_3)
        self.tableWidget1.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidget1.setAlternatingRowColors(True)
        self.tableWidget1.setCornerButtonEnabled(False)
        self.tableWidget1.setRowCount(17)
        self.tableWidget1.setColumnCount(17)
        self.tableWidget1.setObjectName(_fromUtf8("tableWidget1"))
        self.tableWidget1.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget1.horizontalHeader().setDefaultSectionSize(50)
        self.tableWidget1.horizontalHeader().setStretchLastSection(False)
        self.tableWidget1.verticalHeader().setDefaultSectionSize(25)
        self.verticalLayout_3.addWidget(self.tableWidget1)
        self.tabWidget_2.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab_4)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.tableWidget2 = QtGui.QTableWidget(self.tab_4)
        self.tableWidget2.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidget2.setAlternatingRowColors(True)
        self.tableWidget2.setCornerButtonEnabled(False)
        self.tableWidget2.setRowCount(17)
        self.tableWidget2.setColumnCount(17)
        self.tableWidget2.setObjectName(_fromUtf8("tableWidget2"))
        self.tableWidget2.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget2.horizontalHeader().setDefaultSectionSize(50)
        self.tableWidget2.horizontalHeader().setStretchLastSection(False)
        self.tableWidget2.verticalHeader().setDefaultSectionSize(25)
        self.verticalLayout_4.addWidget(self.tableWidget2)
        self.tabWidget_2.addTab(self.tab_4, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.tabWidget_2, 0, 1, 11, 1)
        self.groupBoxFlechas = QtGui.QGroupBox(self.tab)
        self.groupBoxFlechas.setEnabled(False)
        self.groupBoxFlechas.setObjectName(_fromUtf8("groupBoxFlechas"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBoxFlechas)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.comboBoxProv = QtGui.QComboBox(self.groupBoxFlechas)
        self.comboBoxProv.setEnabled(False)
        self.comboBoxProv.setObjectName(_fromUtf8("comboBoxProv"))
        self.verticalLayout_5.addWidget(self.comboBoxProv)
        self.gridLayout_2.addWidget(self.groupBoxFlechas, 7, 0, 1, 1)
        self.label = QtGui.QLabel(self.tab)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 4, 0, 1, 1)
        self.line_2 = QtGui.QFrame(self.tab)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout_2.addWidget(self.line_2, 9, 0, 1, 1)
        self.nextStepBtn = QtGui.QPushButton(self.tab)
        self.nextStepBtn.setEnabled(False)
        self.nextStepBtn.setObjectName(_fromUtf8("nextStepBtn"))
        self.gridLayout_2.addWidget(self.nextStepBtn, 1, 0, 1, 1)
        self.line = QtGui.QFrame(self.tab)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_2.addWidget(self.line, 6, 0, 1, 1)
        self.initialPopulationBtn = QtGui.QPushButton(self.tab)
        self.initialPopulationBtn.setObjectName(_fromUtf8("initialPopulationBtn"))
        self.gridLayout_2.addWidget(self.initialPopulationBtn, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 5, 0, 1, 1)
        self.stopBtn = QtGui.QPushButton(self.tab)
        self.stopBtn.setEnabled(False)
        self.stopBtn.setObjectName(_fromUtf8("stopBtn"))
        self.gridLayout_2.addWidget(self.stopBtn, 3, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 8, 0, 1, 1)
        self.tabWidget_2.raise_()
        self.groupBoxFlechas.raise_()
        self.nextStepBtn.raise_()
        self.simBtn.raise_()
        self.stopBtn.raise_()
        self.nextStepBtn.raise_()
        self.simBtn.raise_()
        self.initialPopulationBtn.raise_()
        self.label.raise_()
        self.groupBoxEventos.raise_()
        self.line.raise_()
        self.line_2.raise_()
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.worldMapBtn = QtGui.QPushButton(self.tab_2)
        self.worldMapBtn.setGeometry(QtCore.QRect(20, 20, 121, 31))
        self.worldMapBtn.setObjectName(_fromUtf8("worldMapBtn"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        SimulationWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(SimulationWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 874, 27))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        SimulationWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(SimulationWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        SimulationWindow.setStatusBar(self.statusbar)

        self.retranslateUi(SimulationWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(SimulationWindow)

    def retranslateUi(self, SimulationWindow):
        SimulationWindow.setWindowTitle(_translate("SimulationWindow", "MainWindow", None))
        self.simBtn.setText(_translate("SimulationWindow", "Simulacion continua", None))
        self.groupBoxEventos.setTitle(_translate("SimulationWindow", "Eventos", None))
        self.label_2.setText(_translate("SimulationWindow", "Provincia", None))
        self.label_3.setText(_translate("SimulationWindow", "Parametro", None))
        self.label_4.setText(_translate("SimulationWindow", "<html><head/><body><p>Cambiar a</p></body></html>", None))
        self.dSpinBoxPerCent.setSuffix(_translate("SimulationWindow", " %", None))
        self.logsBtn.setText(_translate("SimulationWindow", "Logs", None))
        self.updateEventBtn.setText(_translate("SimulationWindow", "Actualizar", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("SimulationWindow", "Cantidad que emigran por provincia", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("SimulationWindow", "Inmigrantes por provincia", None))
        self.groupBoxFlechas.setTitle(_translate("SimulationWindow", "Flechas en el mapa", None))
        self.label.setText(_translate("SimulationWindow", "paso:", None))
        self.nextStepBtn.setText(_translate("SimulationWindow", "Siguiente paso", None))
        self.initialPopulationBtn.setText(_translate("SimulationWindow", "Poblacion inicial", None))
        self.stopBtn.setText(_translate("SimulationWindow", "Pausar simulacion", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("SimulationWindow", "Migraciones Internas", None))
        self.worldMapBtn.setText(_translate("SimulationWindow", "Mapa del Mundo", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("SimulationWindow", "Migraciones Externas", None))

